import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [User, setUser] = useState<string>();
  const [Password, setPassword] = useState<string>();

  const login = async () => {
    const url = "https://vianex.viamericas.io/USA000006/authentication/signin";
    const response = await axios.post(
      url,
      {
        email: "doocando@gmail.com", // User
        password: "Sola1234@", // Password
        devicekey: "12345678",
      }
    );
    console.log("response");
    console.log(JSON.stringify(response));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className={inter.className}>Login</h2>
        <div style={{ width: "80%", margin: "auto" }}>
          <div style={{ margin: "15px 0px" }}>
            <h3 className={inter.className}>Usuario</h3>
            <input
              style={{
                width: "100%",
                fontSize: "20px",
                fontFamily: "monospace",
                padding: "10px",
                margin: "10px 0px 0px 10px",
              }}
              onChange={(value) => setUser(value.target.value)}
            ></input>
          </div>
          <div>
            <h3 className={inter.className}>Contraseña</h3>
            <input
              type="password"
              style={{
                width: "100%",
                fontSize: "20px",
                fontFamily: "monospace",
                padding: "10px",
                margin: "10px 0px 0px 10px",
              }}
              onChange={(value) => setPassword(value.target.value)}
            ></input>
          </div>
          <div>
            <button
              style={{
                padding: "10px 15px",
                minWidth: "125px",
                fontSize: "18px",
                float: "right",
                margin: "10px -10px",
                cursor: "pointer",
              }}
              onClick={login}
            >
              Enviar
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
