import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [User, setUser] = useState<string>();
  const [Password, setPassword] = useState<string>();

  const login = async () => {
    //axios.defaults.xsrfCookieName = 'VA_RME_DEVICE_ID'
    //axios.defaults.xsrfHeaderName = "7252d67b-1fd0-4149-8b46-89d134878d90"
    //axios.defaults.withCredentials = true;
    try{
      const url =
      "https://qa-vianex.viamericas.io/v2/risk/USA000006/authentication/signin";
    const response = await axios.post(url, {
      email: User,
      password: Password,
      devicekey: "",
    },
    {
      headers: {
        'Content-Type': 'application/json',
        //Cookie: 'VA_RME_DEVICE_ID=7252d67b-1fd0-4149-8b46-89d134878d90',
        //withCredentials: true
      },
      //withCredentials: true
    });
    console.log("response");
    console.log(JSON.stringify(response));
    alert(`Response => ${JSON.stringify(response)}`);
    }
    catch(e){
      console.log(e);
      alert("ha ocurrido un error, revisa la consola");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className={inter.className}>Login</h2>
        <div style={{ width: "80%", margin: "auto" }}>
          <div style={{ margin: "15px 0px" }}>
            <h3 className={inter.className}>Usuario</h3>
            <input
              style={{
                width: "100%",
                fontSize: "20px",
                fontFamily: "monospace",
                padding: "10px",
                margin: "10px 0px 0px 10px",
              }}
              onChange={(value) => setUser(value.target.value)}
            ></input>
          </div>
          <div>
            <h3 className={inter.className}>Contraseña</h3>
            <input
              type="password"
              style={{
                width: "100%",
                fontSize: "20px",
                fontFamily: "monospace",
                padding: "10px",
                margin: "10px 0px 0px 10px",
              }}
              onChange={(value) => setPassword(value.target.value)}
            ></input>
          </div>
          <div>
            <button
              style={{
                padding: "10px 15px",
                minWidth: "125px",
                fontSize: "18px",
                float: "right",
                margin: "10px -10px",
                cursor: "pointer",
              }}
              onClick={login}
            >
              Enviar
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
